version: '3.9'

volumes:
  static_value:
  media_value:
  database:

services:

  # back
  backend:
    image: genriber/foodgram-backend:latest
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    restart: always


  # front
  frontend:
    image: genriber/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  # db
  db:
   image: postgres:13.0-alpine
   volumes:
     - database:/var/lib/postgresql/data/
   env_file:
     - .env

  # nginx
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
