version: '3.8'

volumes:
  static_value:
  media_value:
  database:

services:

  # front
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  # db
  db:
   ports: 
     - "5432:5432"
   image: postgres:13.0-alpine
   volumes:
     - database:/var/lib/postgresql/data/
   env_file:
     - ./.env

  # nginx
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
